### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by holzers** [krrish94/nerf-pytorch#1]
First, great work and thanks for making the effort to port this work to pytorch. In the readme you mention a requirements.txt which is used for installing dependencies, but it looks like it is missing in the repository.

**Comment by krrish94** [comment]
Thanks @holzers and nice catch! Pushed `requirements.txt`. Lmk if that works for you.

**Comment by krrish94** [comment]
I've found some time to test the `requirements` file, and it works smoothly. Closing.
