### ISSUE TITLE
Getting 'Killed' whenever trying to train

### ISSUE THREAD

**Issue by joy-alen** [krrish94/nerf-pytorch#15]
Hi,
Whenever I try to train I am getting 'Killed' as an output. This is the same even when trying to cache rays from the output. Can I have some suggestions for resolving this problem?
Thanks in advance.

**Comment by krrish94** [comment]
This might usually mean that python is using more than intended resources (memory usually). If you're running this on a server, be sure to request enough memory

**Comment by joy-alen** [comment]
I'm currently running it on my system. What should be the required amount of memory?

**Comment by krrish94** [comment]
In general that's hard to answer. For tiny configs (eg. Blender datasets, 100 x 100 image resolution, 32 or so samples per ray), I think a computer with 10-12 GB memory, with a GPU of around 2-4 GB memory should be easily able to run this

**Comment by joy-alen** [comment]
Thank you for the answer.
