### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by tobysharp** [krrish94/nerf-pytorch#8]
I followed the instructions in the README. After installing, I ran the command

`python train_nerf.py --config config/lego.yml`

and got the following error
```
Traceback (most recent call last):
  File "train_nerf.py", line 404, in <module>
    main()
  File "train_nerf.py", line 59, in main
    testskip=cfg.dataset.testskip,
  File "D:\dev\nerf\nerf\load_blender.py", line 44, in load_blender_data
    with open(os.path.join(basedir, f"transforms_{s}.json"), "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/nerf_synthetic/lego\\transforms_train.json'
```
This is on Windows with Python 3.7.

**Comment by krrish94** [comment]
Hi, this seems to be a relatively simple issue to fix. Assuming that you've unpacked the data provided by the nerf authors to a folder named `cache` (inside the root directory of the repo), you can edit this line to reflect Windows style paths (i.e., use `\` separators as opposed to `/`). In your case that would be `cache\nerf_synthetic\lego`.

NOTE: You also might want to comment this line out https://github.com/krrish94/nerf-pytorch/blob/master/config/lego.yml#L26

**Comment by tobysharp** [comment]
Can you point me to where it is mentioned to get data and unpack it?

**Comment by krrish94** [comment]
This file should help
https://github.com/bmild/nerf/blob/master/download_example_data.sh

**Comment by tobysharp** [comment]
Very helpful, thanks. Maybe worth mentioning that in the readme.
